# checkout, setup-go, docker/login-action, goreleaser/goreleaser-action, build and push image
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: "1.24.1"

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.2.1
        with:
          version: latest
          args: release --clean --config .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Build and push copatag-action image with new version
        run: |
          tag="$(echo "${{ github.ref }}" | tr -d 'refs/tags/v')"
          docker buildx build \
          --label "org.opencontainers.image.source=https://github.com/sahma19/copatag-action" \
          --label "org.opencontainers.image.description=CLI" \
          --label "org.opencontainers.image.licenses=MIT" \
          -t ghcr.io/sahma19/copatag-action:v"$tag" \
          --push .
